#!/bin/env bash

# a bash script to install nginx
sudo apt-get update

sudo apt-get install -y nginx

sudo service nginx start

sudo sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        echo \"Hello World!\";
    }
}" > /etc/nginx/sites-available/default'

sudo service nginx restart

echo "Nginx has been installed and configured. It is now listening on port 80."
